name 'webapp'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures webapp'
long_description 'Installs/Configures webapp'
version '1.1.6'

depends 'apt', '~> 2.9.2'
depends 'firewall', '~> 2.4.0'
depends 'httpd'
